### PR TITLE
Random Bug fixes 

### PR DESCRIPTION
**Pull request by willtome**

### CODE REVIEW

**Comment by youtous** [comment]
@willtome I have removed the Ansible-lint gh action and replaced it by pre-commit action.
The bug on the ansible-lint action that is preventing us to reference a specific version of the ansible-lint component is referenced by (https://github.com/ansible/ansible-lint/issues/3830)

Using pre-commit as a single point of entry for the linting will ensure consistency for developments (locally and in the CI).

**Comment by jce-redhat** [comment]
Note: the YAML linter complains when comments aren't indented at the same level as the YAML item, which causes some of the lint issues.  this should be configurable in the .yamllint config file, see about disabling this particular feature.

**Comment by jce-redhat** [comment]
> Note: the YAML linter complains when comments aren't indented at the same level as the YAML item, which causes some of the lint issues. this should be configurable in the .yamllint config file, see about disabling this particular feature.

that is, disable [comments-indentation](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments_indentation)

**Comment by youtous** [comment]
TODO:

- [ ] exclude content that is 3rd dep from lint
- [ ] see if comment-indentation for yaml should be disabled: @jce-redhat, what is the rationale behind this? 

thank you for the reviews and the comments

**Review by IPvSean — APPROVED** [review]
I am good with this

**Comment by jce-redhat** [comment]
@youtous for your TODOs, i opened #122 for the first one, and you could add the yamllint config change to #119 since it builds on this PR.

**Pull request merged**
