### PR TITLE
added pre-commit configuration for ansible-lint

### PR DESCRIPTION
**Pull request by jce-redhat**
- updated .ansible-lint
- added .yamllint
- added missing collection used by linux/temp_sudo.yml

no lint errors were fixed in this commit, only the scaffolding for using pre-commit was put in place.

### CODE REVIEW

**Comment by jce-redhat** [comment]
also, the github action ansible/ansible-lint-action@v6.11.0 has not been changed, although it will be reading the new changes to `.ansible-lint`

**Comment by l3acon** [comment]
So this is looking awesome to me. 

I had some trouble around requirements and collections being found, pre-commit seemed to want them in `~/.cache/ansible-compat/ac09d1/collections/ansible_collections/` so I am curious if there is a better way. Perhaps we could provide some guidelines for installing collection dependencies?

**Comment by jce-redhat** [comment]
> I had some trouble around requirements and collections being found, pre-commit seemed to want them in `~/.cache/ansible-compat/ac09d1/collections/ansible_collections/` so I am curious if there is a better way. Perhaps we could provide some guidelines for installing collection dependencies?

if any collections referenced aren't installed in the collections path, ansible-lint  will try to install whatever is in collections/requirements.yml into the ansible-lint cache itself.  since this can take some time, i disabled that in the .ansible-lint config file by setting `offline: true`.  since i already had things in my local cache, i can switch that to `false` and update the PR, that should make local development easier.  just need to make sure that doesn't cause any issues with the github action that runs ansible-lint.

**Comment by jce-redhat** [comment]
just tested with `offline: false` in .ansible-lint.  twice in a row ansible-lint failed to install the collections with the following transient error:

```
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* ansible.controller:4.4.0 (direct request)
```

the third time it succeeded without any changes.  this might be why i switched to `offline: true` in the first place but i can't remember.

so, the tradeoffs for using offline mode or not:

- with `offline: true`, devs will be responsible for populating the local ansible-lint collection cache themselves.
- with `offline: false`, the ansible-lint pre-commit hook should install collections in the local cache, and also in the github action runtime.  the ANSIBLE_GALAXY_SERVER_AH_TOKEN environment variable will need to be populated with a valid token in both cases.  if there are transient issues during github action execution, the github build action will need to be re-run manually.  same for a local commit, although if the cache is already populated i don't think this will occur often.

i'm leaning towards `offline: false` if everyone else is good with it.

**Comment by l3acon** [comment]
I would agree, `offline: true` seems like a better trade-off.

**Review by willtome — APPROVED** [review]

**Pull request merged**
