### PR TITLE
OpenShift Dev Spaces

### PR DESCRIPTION
**Pull request by willtome**
Test Plan:

Step 1: Request OCP from [demo.redhat.com](http://demo.redhat.com/) (https://demo.redhat.com/catalog?item=babylon-catalog-prod/sandboxes-gpte.ocp412-wksp.prod&utm_source=webapp&utm_medium=share-link)
Step 2: When that is ready, launch environment on [red.ht/aap-product-demos](http://red.ht/aap-product-demos)
Step 3: Change project source for official demo project to `devspaces` branch
Step 4: Edit SETUP job template to add extra var `demo: openshift` and disable survey
Step 5 Run SETUP job template
Step 6: Folllow steps here to get OCP token and update OpenShift Credential in Controller (https://github.com/ansible/product-demos/blob/devspaces/openshift/README.md)
Step 7: Run OpenShift / Dev Spaces Job Template

Result: DevSpaces is installed and can be accessed at https://devspaces.apps.<cluster url>

### CODE REVIEW

**Comment by willtome** [comment]
@jeffcpullen
@kyetter

**Comment by willtome** [comment]
blocked by ee without required modules

**Comment by willtome** [comment]
Scrap the original test plan. New Test plan:
Step 1: Request Product Demos Sandbox from demo.redhat.com
Step 2: Change project source for official demo project to devspaces branch
Step 3: Edit SETUP job template to add extra var demo: openshift and disable survey
Step 4: Run SETUP job template

**Comment by dlemons-redhat** [comment]
> Scrap the original test plan. New Test plan: Step 1: Request Product Demos Sandbox from demo.redhat.com Step 2: Change project source for official demo project to devspaces branch Step 3: Edit SETUP job template to add extra var demo: openshift and disable survey Step 4: Run SETUP job template

I followed these steps, Just Works™.  

image

**Review by dlemons-redhat — APPROVED** [review]
tested, approved

**Pull request merged**
