### PR TITLE
Compliance stuff

### PR DESCRIPTION
**Pull request by jce-redhat**
this PR modifies the Linux compliance job template to support multiple security profiles, and adds a job template for reporting compliance against those profiles.

@willtome

### CODE REVIEW

**Review by dlemons-redhat — COMMENTED** [review]
I tried testing these out at red.ht/aap-product-demos .

error : Memory allocation failed : xmlDOMWrapCloneNode(): allocating a node

during the initial compliance report run.  

I'll get a non-Instruqt machine to try against.

**Comment by dlemons-redhat** [comment]
"[WARNING]: - redhatofficial.rhel7_cis was NOT installed successfully: Galaxy",
    "action lookup_role_by_name requires API versions 'v1' but only 'pulp-v3, v3'",
    "are available on server0 https://console.redhat.com/api/automation-",
    "hub/content/6857710-synclist/",
    "ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list."
    
    it looks like we'll have to chase this one down, as well

**Comment by jce-redhat** [comment]
i've only tested against node1 in the instruqt product-demos track at this point, which is RHEL 8.5.  @willtome is going to investigate getting the image updated.  for each profile i've been running an initial report, then enforcing, then re-running a report.  what i've seen so far (again, only on node1 in the instruqt environment):

| profile | report| enforce | re-report |
|--------|-------|---------|----------|
| cis | passed | passed | failed |
| cui | passed | passed | passed |
| hipaa | passed | passed | passed |
| ospp | passed | passed | passed |
| pci-dss | passed | untested | untested |
| stig | failed | untested | untested |

the STIG report failure is because oscap gets OOMkilled (i did test this quickly on a libvirt instance at home and it ran as expected).  for the CIS profile, the re-report fails because on first login, PAM is enforcing a password change.  i haven't dug into the CIS role to see if there's a boolean to disable this for demo purposes.

**Comment by larmbuster** [comment]
Been getting this error when running the STIG Compliance Profile when using the [DOD Automated Compliance Instruqt lab](https://play.instruqt.com/embed/redhat/tracks/dod-automated-compliance?token=em_2u3Z8OGz3pB1m6JJ&show_challenges=true).

`TASK [redhatofficial.rhel8_stig : Security patches are up to date] *************
fatal: [node1]: FAILED! => {"changed": false, "msg": "Failed to download packages: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://cds.rhel.updates.googlecloud.com/pulp/mirror//content/dist/rhel8/rhui/8/x86_64/appstream/os [SSL certificate problem: CA signature digest algorithm too weak]", "results": []}`

**Comment by jce-redhat** [comment]
@larmbuster IIRC that issue is because the image used by the RHEL node is way out of date, and points to a version of RHUI that doesn't support the required digest algorithm.  until the image gets updated, you can run the satellite setup and then run the job template to subscribe node1 to satellite before running the compliance job.

**Comment by jce-redhat** [comment]
having rebase issues, going to close this PR and create a new one

**Pull request closed without merging**
