### PR TITLE
Add OCP-CNV patching demo

### PR DESCRIPTION
**Pull request by l3acon**
This should at least be close to ready to use.

### CODE REVIEW

**Comment by l3acon** [comment]
To do's
- take out machine credential
- check out if RHEL VM entitlements can be automatic
- add wait_for to end of provision of VM
- fix cnv-inventory credential type to have descriptions the same as OCP type
- timing of VM creation & post CNV operator install, chris ran into an issue where the automation tried to create the VM but the images hadn't pulled yet, so they became stale and never provisioned

**Comment by l3acon** [comment]
I have found solutions for both of the timing issues:
*  For validating operator install, we can repeatedly try to provision a VM, when it finally succeeds the operator is finished initializing and ready. 
*  For the inventory sync issue, there is a module, `kubevirt.vm_info` that can be used to wait for a VM to be in the running state. 

Additionally, I discussed with both OCP and RHEL SMEs about subscribing RHEL VMs running on OCP-V. There does not seem to be a more elegant method than using activation keys (or a manifest of some kind).

After what feels like a lifetime ago, I believe this is finally ready for review.

**Review by willtome — APPROVED** [review]
LGTM. Do we need to wait for a new EE build from @cloin before merging?

**Comment by l3acon** [comment]
@IPvSean already merged ee-builds for us. There's that issue you  found with the inventory sync and the demo doesn't function without that. Let me fix before merging.

**Comment by l3acon** [comment]
The [new image](https://github.com/cloin/ee-builds/actions/runs/9469238149/job/26089022071) built. I am going to do a clean slate run through and merge if there are no issues.

**Pull request merged**
