### PR TITLE
Update gitlab version

### PR DESCRIPTION
**Pull request by willtome**
Old chart no longer valid

### CODE REVIEW

**Comment by dlemons-redhat** [comment]
image

worked for me on a product-demos sandbox

**Review by dlemons-redhat — APPROVED** [review]
tested 
image

**Comment by youtous** [comment]
@willtome could you rebase your branch on `main`? It seems it is 6 commits behind it (should fix the CI)

**Comment by youtous** [comment]
I've rebased the PR onto origin/main, LGTM!

**Pull request merged**
