### PR TITLE
⚠ add custom-sized VM to cloud demo

### PR DESCRIPTION
**Pull request by l3acon**

### CODE REVIEW

**Comment by l3acon** [comment]
@jce-redhat this is what I had, it's pretty bare-bones so totally open to suggestions.

**Comment by willtome** [comment]
LGTM

**Review by willtome — APPROVED** [review]

**Comment by jce-redhat** [comment]
it might be simpler to just edit the existing cloud/setup.yml and add a new survey question to the Cloud / AWS / Create VM job template.  the blueprint already specifies the `aws_instance_size` variable for each blueprint, so the new survey question would just override it.

**Comment by jce-redhat** [comment]
i tested this addition to the survey for "Cloud / AWS / Create VM" and it works.  using `require: false` is key so that if no value is provided for the instance type, it will default to whatever is in the VM blueprint.

```
        - question_name: AWS Instance Type (defaults to blueprint value)
          type: text
          variable: aws_instance_size
          required: false
```

**Comment by l3acon** [comment]
That is obviously simpler and better, opened new PR https://github.com/ansible/product-demos/pull/97

**Pull request closed without merging**
